[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/admin/"
  status = 302

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/*"
  to = "/admin/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/admin/"
  status = 200
