# backend:
#   name: github
#   repo: Kmarie85/reclamation-notes-content
#   branch: main
#   auth_type: implicit
#   app_id: 0v23liuLt0LyFciNI6W9

backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "reclamation"
    label: "Reclamation Notes"
    folder: "notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt (optional)", name: "excerpt", widget: "text", required: false }
      - { label: "Featured Image (optional)", name: "featuredImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
